const ShopActionTypes = {
    FETCH_COLLECTION_DATA_START: "FETCH_COLLECTION_DATA_START",
    FETCH_COLLECTION_DATA_SUCCESS: "FETCH_COLLECTION_DATA_SUCCESS",
    FETCH_COLLECTION_DATA_FAILURE: "FETCH_COLLECTION_DATA_FAILURE"
}

export default ShopActionTypes